/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/arrays` | `/arrays`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/binary_search_trees` | `/binary_search_trees`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/binary_trees` | `/binary_trees`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/data_structure` | `/data_structure`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/linked_list` | `/linked_list`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/overview` | `/overview`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/pointers_page` | `/pointers_page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/queues` | `/queues`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/stacks` | `/stacks`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/trees` | `/trees`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(modals)'}/arrays` | `/arrays`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(modals)'}/binary_search_trees` | `/binary_search_trees`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(modals)'}/binary_trees` | `/binary_trees`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(modals)'}/data_structure` | `/data_structure`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(modals)'}/linked_list` | `/linked_list`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(modals)'}/overview` | `/overview`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(modals)'}/pointers_page` | `/pointers_page`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(modals)'}/queues` | `/queues`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(modals)'}/stacks` | `/stacks`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(modals)'}/trees` | `/trees`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(modals)'}/arrays${`?${string}` | `#${string}` | ''}` | `/arrays${`?${string}` | `#${string}` | ''}` | `${'/(modals)'}/binary_search_trees${`?${string}` | `#${string}` | ''}` | `/binary_search_trees${`?${string}` | `#${string}` | ''}` | `${'/(modals)'}/binary_trees${`?${string}` | `#${string}` | ''}` | `/binary_trees${`?${string}` | `#${string}` | ''}` | `${'/(modals)'}/data_structure${`?${string}` | `#${string}` | ''}` | `/data_structure${`?${string}` | `#${string}` | ''}` | `${'/(modals)'}/linked_list${`?${string}` | `#${string}` | ''}` | `/linked_list${`?${string}` | `#${string}` | ''}` | `${'/(modals)'}/overview${`?${string}` | `#${string}` | ''}` | `/overview${`?${string}` | `#${string}` | ''}` | `${'/(modals)'}/pointers_page${`?${string}` | `#${string}` | ''}` | `/pointers_page${`?${string}` | `#${string}` | ''}` | `${'/(modals)'}/queues${`?${string}` | `#${string}` | ''}` | `/queues${`?${string}` | `#${string}` | ''}` | `${'/(modals)'}/stacks${`?${string}` | `#${string}` | ''}` | `/stacks${`?${string}` | `#${string}` | ''}` | `${'/(modals)'}/trees${`?${string}` | `#${string}` | ''}` | `/trees${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/arrays` | `/arrays`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/binary_search_trees` | `/binary_search_trees`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/binary_trees` | `/binary_trees`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/data_structure` | `/data_structure`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/linked_list` | `/linked_list`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/overview` | `/overview`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/pointers_page` | `/pointers_page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/queues` | `/queues`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/stacks` | `/stacks`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/trees` | `/trees`; params?: Router.UnknownInputParams; };
    }
  }
}
